name: CI Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # A cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Custom Script
        run: |
          echo "Running custom script"
         
          node script.js

      - name: Run Tests
        run: npm test
